[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "6a5daf31169f2a2c8d266aaa72737e95ddfa29fc"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "3b9bf53bf9faeda506bf54e48a634f5ba6b351dbb53ff56674b23410a38232a3"
    url = "https://github.com/local/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.x86_64-linux-gnu.tar.gz"
