[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "e1bd42d096f05fe8cdf18e5b84297238b86885d4"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "e7201c349aa307924d3432ec8baba66272fbeb693aacc16cbcff6fc8bc2aa7ea"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.aarch64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "89f20e35ea7b882268772a04730ada0c1d3ae135"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "5f509340f88183cc7dec3b2b3615f1c53dc513f18ba7420d09dbd8c875e63279"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.aarch64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "i686"
git-tree-sha1 = "f7eb4e033277122e38f921b8280b821ab90e586d"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "b696f8ab17582af78667ba4094ab301625eab3a1c7863542b4b28d041bf49d13"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.i686-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "powerpc64le"
git-tree-sha1 = "1c98a4d4b219b0b0c00f5f53e775cbca5d61431b"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "7fb6f2b0b5ebad4a9ea7c56fea0a18b4905650f95a0d0edd66a6a83e55d747ba"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "46fbded08e84031e10ee9d3f325e99a2ba8e770c"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "7c7f1ed536599de440e6c429c89490735addd67707c50f4a62b22ce6dd5057eb"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.x86_64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "b1720b6cf6a414bd8eb9a91a4fa017158ba548f4"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "9abe2448f18ac5cc1f8780ec63d7a1a9e4af6b65c48d3f628da876aaed511f96"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.x86_64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "9d5ef0b76237e8cee128731e683f928b922d4755"
os = "freebsd"

    [[mousetrap_linux.download]]
    sha256 = "d7b3761fb0d0752dd252756de4212c94d6af7e20400271f5824aa8a5fa733e08"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.x86_64-unknown-freebsd.tar.gz"
