[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "9d8bf2d728c2b46fc74d12959dd39e2a78c7986a"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "cf3b282005bfe44f5c6c0dd296d94f971d0ab7bd9c95b9c0c9431c7a90e9c225"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.1+0/mousetrap_linux.v0.2.1.aarch64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "497d1dfc5535c7f3494e9cadf2ffbfcbcf53921a"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "46ed64fb517fe67132a7ec8cdafdb86b1566f0f23787cba36856a6c506c9a50f"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.1+0/mousetrap_linux.v0.2.1.aarch64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "i686"
git-tree-sha1 = "8dcb5985e84ec8cb6c14eb4ce560aecd471fa294"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "86b3aef439cb6cf0f02f443fca8678a579da50a50f7141160ad9ab95ab651135"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.1+0/mousetrap_linux.v0.2.1.i686-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "powerpc64le"
git-tree-sha1 = "505e4e4f23d3cd308319ad5de52f93143202f38a"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "b5af0d72b4602bd2ee5f41266eec8ab747373b201819fc6aa533110046ef99fc"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.1+0/mousetrap_linux.v0.2.1.powerpc64le-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "323e198f4a5b1ab1be1fc36fa37ca1aa06f753aa"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "d1efba2a8d7e78495e7c34a1ce476c74321b1c88c8b6aa837f946b3dac28d213"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.1+0/mousetrap_linux.v0.2.1.x86_64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "be98fe787979ae7a747d8fe7aa3964019d3345c3"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "43e8a053f5b53cbe7638d911a8681664c27284c219cbb9456292861935e7d949"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.1+0/mousetrap_linux.v0.2.1.x86_64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "6662189ae2ea9ec78052cf67bd4f5b1ae99e97a8"
os = "freebsd"

    [[mousetrap_linux.download]]
    sha256 = "44b379e1c25404610e721b3be1bbb41c3d21e8783286d0ad8d5f2c9068874fc6"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.1+0/mousetrap_linux.v0.2.1.x86_64-unknown-freebsd.tar.gz"
