[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "cdd0cd0ba3c63a4312e4bdbe95c37ae5e38748ec"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "c08a964507dd39ae61514a1c05402faf39248d6b267619ee6e5829dfe18675e4"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.aarch64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "f30ddef67abe03414b3cb0a06e26e53430229f49"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "e3d304ba500dd2d3ab99dfdd516b123caf47badc8f6d67ac10a3424360f1b6e7"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.aarch64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "i686"
git-tree-sha1 = "6baa608303736fb96bc68bb4b625dd6543662d34"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "a435600fde08740d6c5f504350b6b6254e4716af135944164fd6d50ee621557b"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.i686-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "powerpc64le"
git-tree-sha1 = "27554e069c3c987720c799fbda154de0c0061b8a"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "22507cccedcc4f41bce7a39ca2c0900ab81995e0d8d7272a5190f75863c60d5e"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.powerpc64le-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "63e92f9c6ab0357e1e24acd7fc7cc7a22de166ca"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "bdd38b5036f1955a92da7bdcc2fda440e415b58f400fc3b68779b8ed9304e841"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.x86_64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "d733b4e02e6218b1d66280728423cb22b1b1aa0b"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "339e6118c4d613cbc005f09b428ff129881674f3055a2778d2db4e2ad8fa9fb3"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.x86_64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "b8387a6d9143edafe876ec81eeb5c3a63d96edab"
os = "freebsd"

    [[mousetrap_linux.download]]
    sha256 = "3951d33489e3fdea6fa38f2cd5a6d2f0b16d23a27736cc710c25cebf61d64c2e"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.2.0+0/mousetrap_linux.v0.2.0.x86_64-unknown-freebsd.tar.gz"
