[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "4b3b3405001879badf06a223c3f0af6d51aba8c3"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "f355f284bce90a0ea13107312f7c56096c3f11471f1a19aec992cf8ca3111e73"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.aarch64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "aarch64"
git-tree-sha1 = "96dbe013854006b9a960cbde418f708778fe8634"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "0b8cb5b737357bf6511779a900ec3a2ee0985910de8a33f6f8f055f45a1e72b6"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.aarch64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "i686"
git-tree-sha1 = "a0a39ef42d07eb64ffe618ae6bacd4987c521483"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "ab247b23f9627217d2d96546eec3ef8110b35e074c10d1d3779b003e06e656c0"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.i686-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "powerpc64le"
git-tree-sha1 = "1d6e2d1c71ab789d8fbf1fe84702d3fbbada26de"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "1cb14bf07b9f961d4d5dfcb13c056332e6c44bdbcd222447cae8d244dba9ba96"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "1c1f06ce2383c6682f3e5ba47e220293a0dcac70"
libc = "glibc"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "7a31fc240a181c8a92d3a7672e578a658c290b8f5bd8352ba3252682a26bb6f8"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.x86_64-linux-gnu.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "5b0af01b26232f88920e164bf691fa2a03434bb2"
libc = "musl"
os = "linux"

    [[mousetrap_linux.download]]
    sha256 = "fb5694e33954793c1587eb325188f313f7b0a4e8d6ed122fb750882312fe39eb"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.x86_64-linux-musl.tar.gz"
[[mousetrap_linux]]
arch = "x86_64"
git-tree-sha1 = "1e713f01c4931f922a32dee69f76111287015458"
os = "freebsd"

    [[mousetrap_linux.download]]
    sha256 = "956cb31b42f55465267bb8e592843e632fe56af5e4f2b2631e5f67166a91767b"
    url = "https://github.com/Clemapfel/mousetrap_linux_jll/releases/download/mousetrap_linux-v0.1.1+0/mousetrap_linux.v0.1.1.x86_64-unknown-freebsd.tar.gz"
