# Autogenerated wrapper script for mousetrap_linux_jll for x86_64-linux-gnu
export mousetrap_julia_binding_linux, mousetrap_linux

using GLEW_jll
using GTK4_jll
using OpenGLMathematics_jll
using GLU_jll
using libcxxwrap_julia_jll
using libjulia_jll
JLLWrappers.@generate_wrapper_header("mousetrap_linux")
JLLWrappers.@declare_library_product(mousetrap_julia_binding_linux, "libmousetrap_julia_binding.so")
JLLWrappers.@declare_library_product(mousetrap_linux, "libmousetrap.so")
function __init__()
    JLLWrappers.@generate_init_header(GLEW_jll, GTK4_jll, OpenGLMathematics_jll, GLU_jll, libcxxwrap_julia_jll, libjulia_jll)
    JLLWrappers.@init_library_product(
        mousetrap_julia_binding_linux,
        "lib/libmousetrap_julia_binding.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        mousetrap_linux,
        "lib/libmousetrap.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
